apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
  labels:
    app: goserver
spec:  
  selector: # selector acessar a label que tenha o nome, filtrar para verificar
    matchLabels:
      app: goserver
  replicas: 10
  template:
    metadata:
      labels: # eu posso ter vários Pod com a mesma label, assim posso filtras os meus pods 
          app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image : "ronaldoapsilva85/hello-go:v2"